### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by blackknight36**
This branch includes unit tests for each class and defined type in this module.  I've also included a few other commits which contain changes I had to make to get rspec tests to run successfully.

### CODE REVIEW

**Review by jflorian — COMMENTED** [review]
Looks like there's some copy/paste baggage in `spec/spec_helper.rb` -- see the `add_custom_fact` stuff.

**Review by jflorian — COMMENTED** [review]
I found it necessary to use `operatingsystemMAJrelease` to avoid warnings (r10k IIRC).  The alternative, I think, would be to list every EL 7.x release which makes for a lot of busy work.  Ideas?

**Comment by blackknight36** [comment]
I'll have to clean things up and resubmit.  As far as the metadata file is concerned the puppet documentation only mentions using operatingsystemrelease although you can also specify a minor release in that field according to the examples provided at https://puppet.com/docs/puppet/5.3/modules_metadata.html#specifying-operating-system-compatibility-in-modules

**Comment by blackknight36** [comment]
I've cleaned up the spec_helper classes and rebased this off the current develop branch.

**Comment by jflorian** [comment]
@blackknight36 Are you familiar with what's needed to have these tests running automatically here on GitHub?

**Comment by blackknight36** [comment]
@jflorian Not exactly.  I believe you need to enable TravisCI and then set up a .travis.yml and/or Vagrant files.  .travis.yml should look something like this.

```
---
language: ruby
bundler_args: --without development
cache: bundler
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.9.3
  - 2.1.0
script: bundle exec rake test
env:
env:
  - PUPPET_GEM_VERSION="~> 3.8.0" FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
```

https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci has some useful info as well.

I've mostly been doing CI with Jenkins, I can provide some project configuration files if you want to set that up.

**Pull request merged**
